on:
  workflow_call:
    inputs:
      builder:
        type: string
        required: true
      luamem_lib_path:
        type: string
        required: true
      luamem_lib_name:
        type: string
        default: luamem
      luarocks:
        type: boolean
        default: false

jobs:

  test:

    strategy:
      matrix:
        platform:
        - ubuntu-latest
        - macos-latest
        - windows-latest
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@master

    - uses: ilammy/msvc-dev-cmd@v1
      if: ${{ contains(matrix.platform, 'windows') }}
    - uses: leafo/gh-actions-lua@v11
      with:
        luaVersion: "5.4"

    - uses: luarocks/gh-actions-luarocks@master
      if: ${{ inputs.luarocks }}

    - name: build
      run: ${{ inputs.builder }}

    - name: test-lib-linux
      if: ${{ contains(matrix.platform, 'ubuntu') }}
      run: |
        gcc -o test/memory_test.so test/ltestlib.c \
            --shared \
            -fPIC -DLUA_USE_MACOSX -Isrc -I.lua/include

    - name: test-lib-macos
      if: ${{ contains(matrix.platform, 'macos') }}
      run: |
        export MACOSX_DEPLOYMENT_TARGET="10.10"; \
        gcc -o test/memory_test.so test/ltestlib.c \
            -bundle -undefined dynamic_lookup \
            -fno-common -DLUA_USE_MACOSX -Isrc -I.lua/include

    - name: test-lib-win
      if: ${{ contains(matrix.platform, 'windows') }}
      shell: cmd
      run: |
        if "${{ inputs.luamem_lib_path }}"=="MEMORY_ROCK" (
          for /F "tokens=* USEBACKQ" %%F in (`luarocks show --rock-dir memory`) do (
            set MEMORY_LIBDIR=%%F\library
          )
        ) else (
          set MEMORY_LIBDIR=${{ inputs.luamem_lib_path }}
        )

        cl.exe /nologo /Isrc /I.lua\include /c test\ltestlib.c /Fo:test\ltestlib.obj
        link.exe /nologo /dll /out:test\memory_test.dll ^
                 /LIBPATH:.lua\lib /LIBPATH:%MEMORY_LIBDIR% ^
                 test\ltestlib.obj lua54.lib ${{ inputs.luamem_lib_name }}.lib

    - name: test
      run: cd test && lua testall.lua
